### ISSUE TITLE
Adaptec 5805: cannot parse as a valid JSON object.

### ISSUE THREAD

**Issue by YgRex2020** [nikimaxim/zbx-raid-controller#10]
Привет!
Скрипт не может собрать нормально информацию по данному контроллеру. По контроллерам 6, 7, 8 поколения нет. Похоже проблема в том, что на 5805 есть два девайса Enclosure Services Device.

      Device #8
         Device is an Enclosure Services Device
         Reported Channel,Device(T:L)         : 2,0(0:0)
         Enclosure ID                         : 0
         Type                                 : SES2
         Vendor                               : ADAPTEC
         Model                                : Virtual SGPIO
         Firmware                             : 0001
         Status of Enclosure Services Device
            Speaker status                    : Not Available
      Device #9
         Device is an Enclosure Services Device
         Reported Channel,Device(T:L)         : 2,1(1:0)
         Enclosure ID                         : 1
         Type                                 : SES2
         Vendor                               : ADAPTEC
         Model                                : Virtual SGPIO
         Firmware                             : 0001
         Status of Enclosure Services Device
            Speaker status                    : Not Available

![PD_error2](https://user-images.githubusercontent.com/69971631/195788430-ea77ff06-1fa6-4e76-88ab-ae3e7488aaba.jpg)
![PD_error1](https://user-images.githubusercontent.com/69971631/195788439-f57b3b58-48ca-4500-941d-435ba1b5a7b7.jpg)

Как это можно исправить?

Спасибо!

**Comment by nikimaxim** [comment]
@YgRex2020 
Добрый день.

Можете скинуть вывод команд(txt файлом):
`powershell -NoProfile -NoLogo -ExecutionPolicy Bypass -File "C:\service\adaptec-raid.ps1" lld ad`

И

`arcconf.exe  LIST`
`arcconf.exe  GETCONFIG 1 AD`
`arcconf.exe  GETCONFIG 1 PD`
`arcconf.exe  GETCONFIG 1 LD`

**Comment by YgRex2020** [comment]
Приветствую!

Вот то, что просили.

C:\Windows\system32>powershell  -NoProfile -NoLogo -ExecutionPolicy Bypass -File
 "C:\zabbix\scripts\adaptec-raid.ps1" lld ad
{"data":[{"{#[CTRL.ID](http://ctrl.id/)}":"1","{#CTRL.MODEL}":"-","{#[CTRL.SN](http://ctrl.sn/)}":"1D3511BB64E"}]}

==================================================================================

C:\zabbix\diskutils\Arcconf>arcconf.exe LIST
Controllers found: 1
----------------------------------------------------------------------
Controller information
----------------------------------------------------------------------
   Controller ID             : Status, Slot, Mode, Name, SerialNumber, WWN
----------------------------------------------------------------------
   Controller 1:             : Optimal, Slot 1, RAID (Expose RAW), Adaptec Adapt
ec 5805, 1D3511BB64E, 50000D1104619780

Command completed successfully.

==================================================================================


Controllers found: 1
----------------------------------------------------------------------
Controller information
----------------------------------------------------------------------
   Controller Status                          : Optimal
   Channel description                        : SAS/SATA
   Controller Model                           : Adaptec Adaptec 5805
   Controller Serial Number                   : 1D3511BB64E
   Controller World Wide Name                 : 50000D1104619780
   Controller Alarm                           : Enabled
   Physical Slot                              : 1
   Temperature                                : 84 C/ 183 F (Normal)
   Installed memory                           : 512 MB
   Host bus type                              : PCIe
   Host bus speed                             : 2500 MHz
   Host bus link width                        : 8 bit(s)/link(s)
   Global task priority                       : High
   Performance Mode                           : Default/Dynamic
   PCI Device ID                              : 645
   Stayawake period                           : Disabled
   Spinup limit internal drives               : 0
   Spinup limit external drives               : 0
   Defunct disk drive count                   : 0
   NCQ status                                 : Enabled
   Statistics data collection mode            : Enabled
   --------------------------------------------------------
   Cache Properties
   --------------------------------------------------------
   --------------------------------------------------------
   maxCache Properties
   --------------------------------------------------------
   SSDs assigned to maxCache pool             : 0
   Maximum SSDs allowed in maxCache pool      : 8
   maxCache Read Cache Pool Size              : 0.000 GB
   maxCache flush and fetch rate              : 0
   maxCache Read, Write Balance Factor        : 3,1
   --------------------------------------------------------
   RAID Properties
   --------------------------------------------------------
   Logical devices/Failed/Degraded            : 1/0/0
   Copyback                                   : Disabled
   Automatic Failover                         : Enabled
   Background consistency check               : Enabled
   Background consistency check period        : 30
   --------------------------------------------------------
   Controller Version Information
   --------------------------------------------------------
   BIOS                                       : 5.2-0 (18252)
   Firmware                                   : 5.2-0 (18252)
   Driver                                     : 7.2-0 (30261)
   Boot Flash                                 : 5.2-0 (18252)
   --------------------------------------------------------
   Controller Battery Information
   --------------------------------------------------------
   Status                                     : Failed
   --------------------------------------------------------
   Connector information
                     
   --------------------------------------------------------
   Connector #0                               
      Connector Name                          : CN0

      ----------------------------------------
   Lane Information                           
      ----------------------------------------
      Lane #0                                 
         Channel ID                           : 0
         Device ID                            : 0
         SAS Address                          : 50000D1104619780
         PHY Identifier                       : 3
         -------------------------------------
         Lane SAS Phy Information             
         -------------------------------------
            SAS Address                       : 50000D1104619780
            Attached PHY Identifier           : 0
            Attached SAS Address              : 5000C5008D75E5C1
            Negotiated Logical Link Rate      : PHY enabled - 3 Gbps

      Lane #1                                 
         Channel ID                           : 0
         Device ID                            : 1
         SAS Address                          : 50000D1104619780
         PHY Identifier                       : 1
         -------------------------------------
         Lane SAS Phy Information             
         -------------------------------------
            SAS Address                       : 50000D1104619780
            Attached PHY Identifier           : 0
            Attached SAS Address              : 5000C5008D75EA0D
            Negotiated Logical Link Rate      : PHY enabled - 3 Gbps

      Lane #2                                 
         Channel ID                           : 0
         Device ID                            : 2
         SAS Address                          : 50000D1104619780
         PHY Identifier                       : 0
         -------------------------------------
         Lane SAS Phy Information             
         -------------------------------------
            SAS Address                       : 50000D1104619780
            Attached PHY Identifier           : 0
            Attached SAS Address              : 5000C5008D762479
            Negotiated Logical Link Rate      : PHY enabled - 3 Gbps

      Lane #3                                 
         Channel ID                           : 0
         Device ID                            : 3
         SAS Address                          : 50000D1104619780
         PHY Identifier                       : 2
         -------------------------------------
         Lane SAS Phy Information             
         -------------------------------------
            SAS Address                       : 50000D1104619780
            Attached PHY Identifier           : 0
            Attached SAS Address              : 5000C5008D762465
            Negotiated Logical Link Rate      : PHY enabled - 3 Gbps


   Connector #1                               
      Connector Name                          : CN1

      ----------------------------------------
   Lane Information                           
      ----------------------------------------
      Lane #0                                 
         Channel ID                           : 0
         Device ID                            : 4
         SAS Address                          : 50000D1104619780
         PHY Identifier                       : 6
         -------------------------------------
         Lane SAS Phy Information             
         -------------------------------------
            SAS Address                       : 50000D1104619780
            Attached PHY Identifier           : 0
            Attached SAS Address              : 5000C5008D7624D9
            Negotiated Logical Link Rate      : PHY enabled - 3 Gbps

      Lane #1                                 
         Channel ID                           : 0
         Device ID                            : 5
         SAS Address                          : 50000D1104619780
         PHY Identifier                       : 4
         -------------------------------------
         Lane SAS Phy Information             
         -------------------------------------
            SAS Address                       : 50000D1104619780
            Attached PHY Identifier           : 0
            Attached SAS Address              : 5000C5008D75E055
            Negotiated Logical Link Rate      : PHY enabled - 3 Gbps

      Lane #2                                 
         Channel ID                           : 0
         Device ID                            : 6
         SAS Address                          : 50000D1104619780
         PHY Identifier                       : 5
         -------------------------------------
         Lane SAS Phy Information             
         -------------------------------------
            SAS Address                       : 50000D1104619780
            Attached PHY Identifier           : 0
            Attached SAS Address              : 5000C5008D762399
            Negotiated Logical Link Rate      : PHY enabled - 3 Gbps

      Lane #3                                 
         Channel ID                           : 0
         Device ID                            : 7
         SAS Address                          : 50000D1104619780
         PHY Identifier                       : 7
         -------------------------------------
         Lane SAS Phy Information             
         -------------------------------------
            SAS Address                       : 50000D1104619780
            Attached PHY Identifier           : 0
            Attached SAS Address              : 5000C5008D75D875
            Negotiated Logical Link Rate      : PHY enabled - 3 Gbps




Command completed successfully.

=========================================================================================


Controllers found: 1
----------------------------------------------------------------------
Physical Device information
----------------------------------------------------------------------
      Device #0
         Device is a Hard drive
         State                                : Online
         Block Size                           : 512 Bytes
         Supported                            : Yes
         Transfer Speed                       : SAS 3.0 Gb/s
         Reported Channel,Device(T:L)         : 0,0(0:0)
         Reported Location                    : Enclosure 0, Slot 0( Connector Unknown )
         Reported ESD(T:L)                    : 2,0(0:0)
         Vendor                               : SEAGATE
         Model                                : ST300MP0005
         Firmware                             : N004
         Serial number                        : S7K0NCFH0000M6127011
         World-wide name                      : 5000C5008D75E5C0
         Reserved Size                        : 415982 KB
         Used Size                            : 285696 MB
         Unused Size                          : 64 KB
         Total Size                           : 286102 MB
         Write Cache                          : Enabled (write-back)
         FRU                                  : None
         S.M.A.R.T.                           : No
         S.M.A.R.T. warnings                  : 0
         Power State                          : Full rpm
         Supported Power States               : Full rpm,Powered off
         SSD                                  : No
         maxCache Capable                     : No
         maxCache Assigned                    : No
         Temperature                          : Not Supported
      ----------------------------------------------------------------
      Device Phy Information                  
      ----------------------------------------------------------------
         Phy #0
            PHY Identifier                    : 0
            SAS Address                       : 5000C5008D75E5C1
            Attached PHY Identifier           : 3
            Attached SAS Address              : 50000D1104619780
         Phy #1
            PHY Identifier                    : 1
            SAS Address                       : 5000C5008D75E5C2

      Device #1
         Device is a Hard drive
         State                                : Online
         Block Size                           : 512 Bytes
         Supported                            : Yes
         Transfer Speed                       : SAS 3.0 Gb/s
         Reported Channel,Device(T:L)         : 0,1(1:0)
         Reported Location                    : Enclosure 0, Slot 1( Connector Unknown )
         Reported ESD(T:L)                    : 2,0(0:0)
         Vendor                               : SEAGATE
         Model                                : ST300MP0005
         Firmware                             : N004
         Serial number                        : S7K0JE0V0000M608FZXY
         World-wide name                      : 5000C5008D75EA0C
         Reserved Size                        : 415982 KB
         Used Size                            : 285696 MB
         Unused Size                          : 64 KB
         Total Size                           : 286102 MB
         Write Cache                          : Enabled (write-back)
         FRU                                  : None
         S.M.A.R.T.                           : No
         S.M.A.R.T. warnings                  : 0
         Power State                          : Full rpm
         Supported Power States               : Full rpm,Powered off
         SSD                                  : No
         maxCache Capable                     : No
         maxCache Assigned                    : No
         Temperature                          : Not Supported
      ----------------------------------------------------------------
      Device Phy Information                  
      ----------------------------------------------------------------
         Phy #0
            PHY Identifier                    : 0
            SAS Address                       : 5000C5008D75EA0D
            Attached PHY Identifier           : 1
            Attached SAS Address              : 50000D1104619780
         Phy #1
            PHY Identifier                    : 1
            SAS Address                       : 5000C5008D75EA0E

      Device #2
         Device is a Hard drive
         State                                : Online
         Block Size                           : 512 Bytes
         Supported                            : Yes
         Transfer Speed                       : SAS 3.0 Gb/s
         Reported Channel,Device(T:L)         : 0,2(2:0)
         Reported Location                    : Enclosure 0, Slot 2( Connector Unknown )
         Reported ESD(T:L)                    : 2,0(0:0)
         Vendor                               : SEAGATE
         Model                                : ST300MP0005
         Firmware                             : N004
         Serial number                        : S7K00C8M0000S442SZ38
         World-wide name                      : 5000C5008D762478
         Reserved Size                        : 415982 KB
         Used Size                            : 285696 MB
         Unused Size                          : 64 KB
         Total Size                           : 286102 MB
         Write Cache                          : Enabled (write-back)
         FRU                                  : None
         S.M.A.R.T.                           : No
         S.M.A.R.T. warnings                  : 0
         Power State                          : Full rpm
         Supported Power States               : Full rpm,Powered off
         SSD                                  : No
         maxCache Capable                     : No
         maxCache Assigned                    : No
         Temperature                          : Not Supported
      ----------------------------------------------------------------
      Device Phy Information                  
      ----------------------------------------------------------------
         Phy #0
            PHY Identifier                    : 0
            SAS Address                       : 5000C5008D762479
            Attached PHY Identifier           : 0
            Attached SAS Address              : 50000D1104619780
         Phy #1
            PHY Identifier                    : 1
            SAS Address                       : 5000C5008D76247A

      Device #3
         Device is a Hard drive
         State                                : Online
         Block Size                           : 512 Bytes
         Supported                            : Yes
         Transfer Speed                       : SAS 3.0 Gb/s
         Reported Channel,Device(T:L)         : 0,3(3:0)
         Reported Location                    : Enclosure 0, Slot 3( Connector Unknown )
         Reported ESD(T:L)                    : 2,0(0:0)
         Vendor                               : SEAGATE
         Model                                : ST300MP0005
         Firmware                             : N004
         Serial number                        : S7K00CBK0000S442SZ49
         World-wide name                      : 5000C5008D762464
         Reserved Size                        : 415982 KB
         Used Size                            : 285696 MB
         Unused Size                          : 64 KB
         Total Size                           : 286102 MB
         Write Cache                          : Enabled (write-back)
         FRU                                  : None
         S.M.A.R.T.                           : No
         S.M.A.R.T. warnings                  : 0
         Power State                          : Full rpm
         Supported Power States               : Full rpm,Powered off
         SSD                                  : No
         maxCache Capable                     : No
         maxCache Assigned                    : No
         Temperature                          : Not Supported
      ----------------------------------------------------------------
      Device Phy Information                  
      ----------------------------------------------------------------
         Phy #0
            PHY Identifier                    : 0
            SAS Address                       : 5000C5008D762465
            Attached PHY Identifier           : 2
            Attached SAS Address              : 50000D1104619780
         Phy #1
            PHY Identifier                    : 1
            SAS Address                       : 5000C5008D762466

      Device #4
         Device is a Hard drive
         State                                : Online
         Block Size                           : 512 Bytes
         Supported                            : Yes
         Transfer Speed                       : SAS 3.0 Gb/s
         Reported Channel,Device(T:L)         : 0,4(4:0)
         Reported Location                    : Enclosure 1, Slot 4( Connector Unknown )
         Reported ESD(T:L)                    : 2,1(1:0)
         Vendor                               : SEAGATE
         Model                                : ST300MP0005
         Firmware                             : N004
         Serial number                        : S7K00C250000S44297BW
         World-wide name                      : 5000C5008D7624D8
         Reserved Size                        : 415982 KB
         Used Size                            : 285696 MB
         Unused Size                          : 64 KB
         Total Size                           : 286102 MB
         Write Cache                          : Enabled (write-back)
         FRU                                  : None
         S.M.A.R.T.                           : No
         S.M.A.R.T. warnings                  : 0
         Power State                          : Full rpm
         Supported Power States               : Full rpm,Powered off
         SSD                                  : No
         maxCache Capable                     : No
         maxCache Assigned                    : No
         Temperature                          : Not Supported
      ----------------------------------------------------------------
      Device Phy Information                  
      ----------------------------------------------------------------
         Phy #0
            PHY Identifier                    : 0
            SAS Address                       : 5000C5008D7624D9
            Attached PHY Identifier           : 6
            Attached SAS Address              : 50000D1104619780
         Phy #1
            PHY Identifier                    : 1
            SAS Address                       : 5000C5008D7624DA

      Device #5
         Device is a Hard drive
         State                                : Online
         Block Size                           : 512 Bytes
         Supported                            : Yes
         Transfer Speed                       : SAS 3.0 Gb/s
         Reported Channel,Device(T:L)         : 0,5(5:0)
         Reported Location                    : Enclosure 1, Slot 5( Connector Unknown )
         Reported ESD(T:L)                    : 2,1(1:0)
         Vendor                               : SEAGATE
         Model                                : ST300MP0005
         Firmware                             : N004
         Serial number                        : S7K100X50000K609790G
         World-wide name                      : 5000C5008D75E054
         Reserved Size                        : 415982 KB
         Used Size                            : 285696 MB
         Unused Size                          : 64 KB
         Total Size                           : 286102 MB
         Write Cache                          : Enabled (write-back)
         FRU                                  : None
         S.M.A.R.T.                           : No
         S.M.A.R.T. warnings                  : 0
         Power State                          : Full rpm
         Supported Power States               : Full rpm,Powered off
         SSD                                  : No
         maxCache Capable                     : No
         maxCache Assigned                    : No
         Temperature                          : Not Supported
      ----------------------------------------------------------------
      Device Phy Information                  
      ----------------------------------------------------------------
         Phy #0
            PHY Identifier                    : 0
            SAS Address                       : 5000C5008D75E055
            Attached PHY Identifier           : 4
            Attached SAS Address              : 50000D1104619780
         Phy #1
            PHY Identifier                    : 1
            SAS Address                       : 5000C5008D75E056

      Device #6
         Device is a Hard drive
         State                                : Online
         Block Size                           : 512 Bytes
         Supported                            : Yes
         Transfer Speed                       : SAS 3.0 Gb/s
         Reported Channel,Device(T:L)         : 0,6(6:0)
         Reported Location                    : Enclosure 1, Slot 6( Connector Unknown )
         Reported ESD(T:L)                    : 2,1(1:0)
         Vendor                               : SEAGATE
         Model                                : ST300MP0005
         Firmware                             : N004
         Serial number                        : S7K00CCP0000S444V2LJ
         World-wide name                      : 5000C5008D762398
         Reserved Size                        : 415982 KB
         Used Size                            : 285696 MB
         Unused Size                          : 64 KB
         Total Size                           : 286102 MB
         Write Cache                          : Enabled (write-back)
         FRU                                  : None
         S.M.A.R.T.                           : No
         S.M.A.R.T. warnings                  : 0
         Power State                          : Full rpm
         Supported Power States               : Full rpm,Powered off
         SSD                                  : No
         maxCache Capable                     : No
         maxCache Assigned                    : No
         Temperature                          : Not Supported
      ----------------------------------------------------------------
      Device Phy Information                  
      ----------------------------------------------------------------
         Phy #0
            PHY Identifier                    : 0
            SAS Address                       : 5000C5008D762399
            Attached PHY Identifier           : 5
            Attached SAS Address              : 50000D1104619780
         Phy #1
            PHY Identifier                    : 1
            SAS Address                       : 5000C5008D76239A

      Device #7
         Device is a Hard drive
         State                                : Global Hot-Spare
         Block Size                           : 512 Bytes
         Supported                            : Yes
         Transfer Speed                       : SAS 3.0 Gb/s
         Reported Channel,Device(T:L)         : 0,7(7:0)
         Reported Location                    : Enclosure 1, Slot 7( Connector Unknown )
         Reported ESD(T:L)                    : 2,1(1:0)
         Vendor                               : SEAGATE
         Model                                : ST300MP0005
         Firmware                             : N004
         Serial number                        : S7K0SZ8W0000K61569J7
         World-wide name                      : 5000C5008D75D874
         Reserved Size                        : 415982 KB
         Used Size                            : 285696 MB
         Unused Size                          : 64 KB
         Total Size                           : 286102 MB
         Write Cache                          : Enabled (write-back)
         FRU                                  : None
         S.M.A.R.T.                           : No
         S.M.A.R.T. warnings                  : 0
         Power State                          : Full rpm
         Supported Power States               : Full rpm,Powered off
         SSD                                  : No
         maxCache Capable                     : No
         maxCache Assigned                    : No
         Temperature                          : Not Supported
      ----------------------------------------------------------------
      Device Phy Information                  
      ----------------------------------------------------------------
         Phy #0
            PHY Identifier                    : 0
            SAS Address                       : 5000C5008D75D875
            Attached PHY Identifier           : 7
            Attached SAS Address              : 50000D1104619780
         Phy #1
            PHY Identifier                    : 1
            SAS Address                       : 5000C5008D75D876

      Device #8
         Device is an Enclosure Services Device
         Reported Channel,Device(T:L)         : 2,0(0:0)
         Enclosure ID                         : 0
         Type                                 : SES2
         Vendor                               : ADAPTEC
         Model                                : Virtual SGPIO
         Firmware                             : 0001
         Status of Enclosure Services Device
            Speaker status                    : Not Available
      Device #9
         Device is an Enclosure Services Device
         Reported Channel,Device(T:L)         : 2,1(1:0)
         Enclosure ID                         : 1
         Type                                 : SES2
         Vendor                               : ADAPTEC
         Model                                : Virtual SGPIO
         Firmware                             : 0001
         Status of Enclosure Services Device
            Speaker status                    : Not Available


Command completed successfully.



==========================================================================================

Controllers found: 1
----------------------------------------------------------------------
Logical device information
----------------------------------------------------------------------
Logical Device number 0
   Logical Device name                        : RAID5
   Block Size of member drives                : 512 Bytes
   RAID level                                 : 5
   Unique Identifier                          : 009AB529
   Status of Logical Device                   : Optimal
   Additional details                         : Quick initialized
   Size                                       : 1714166 MB
   Parity space                               : 285696 MB
   Stripe-unit size                           : 16 KB
   Interface Type                             : Serial Attached SCSI
   Device Type                                : HDD
   Read-cache setting                         : Enabled
   Read-cache status                          : On
   Write-cache setting                        : Enabled
   Write-cache status                         : On
   maxCache read cache setting                : Enabled
   maxCache read cache status                 : Off
   Partitioned                                : Yes
   Protected by Hot-Spare                     : Yes
   Global Hot-Spare                           : 0,7
   Bootable                                   : Yes
   Failed stripes                             : No
   Power settings                             : Disabled
   --------------------------------------------------------
   Logical Device segment information
   --------------------------------------------------------
   Segment 0                                  : Present (286102MB, SAS, HDD, Enclosure:0, Slot:0) S7K0NCFH0000M6127011
   Segment 1                                  : Present (286102MB, SAS, HDD, Enclosure:0, Slot:1) S7K0JE0V0000M608FZXY
   Segment 2                                  : Present (286102MB, SAS, HDD, Enclosure:0, Slot:2) S7K00C8M0000S442SZ38
   Segment 3                                  : Present (286102MB, SAS, HDD, Enclosure:0, Slot:3) S7K00CBK0000S442SZ49
   Segment 4                                  : Present (286102MB, SAS, HDD, Enclosure:1, Slot:4) S7K00C250000S44297BW
   Segment 5                                  : Present (286102MB, SAS, HDD, Enclosure:1, Slot:5) S7K100X50000K609790G
   Segment 6                                  : Present (286102MB, SAS, HDD, Enclosure:1, Slot:6) S7K00CCP0000S444V2LJ



Command completed successfully.

**Comment by nikimaxim** [comment]
@YgRex2020 
Добрый день
Изменения в репозитории проверьте. 
https://github.com/nikimaxim/zbx-raid-controller/commit/26f36570e73ea7412b6434a151023b92970ac30a

Спасибо

**Comment by YgRex2020** [comment]
Спасибо! Долго не заглядывал. Наш коллега вот так поправил код скрипта. Работает.
[adaptec-raid.txt](https://github.com/nikimaxim/zbx-raid-controller/files/10003205/adaptec-raid.txt)
