### ISSUE TITLE
Unknown metric adaptec.raid

### ISSUE THREAD

**Issue by bcnx** [nikimaxim/zbx-raid-controller#5]
Hi,

I have this issue when running this:

`zabbix_agent2.exe -t "adaptec.raid[health,pd,1,0]"`

when I run this (which is in my Userparameter content), it works perfectly:

`powershell -NoProfile -NoLogo -ExecutionPolicy Bypass -File "C:\install\zabbix\adaptec-raid.ps1" health pd 1 0`

Any idea where this goes wrong?

Cheers!

BC

**Comment by bcnx** [comment]
OK, it seems zabbix_agent2.exe requires the -c parameter, if not it will look for a conf file that does not exist. 
At this point it is not clear however why Zabbix does not show any data for the adaptec.raid items. The discovery items seem to work but no data is queried for the drives.

BC

**Comment by nikimaxim** [comment]
@bcnx Hi.
Can I close it?

**Comment by bcnx** [comment]
Hi, yes, this issue can be closed. I stopped getting data for the physical drives, but for that I will try to reopen another issue or create a new one.

Cheers,

BC
